### PR TITLE
Implement `ptx_dispatch` for if-target compatible target specialization

### PR DESCRIPTION
**Pull request by allisonvacanti**

### CODE REVIEW

File: cmake/CubCudaConfig.cmake [hunk 1]
```diff
@@ -128,6 +130,17 @@ endif()
...
 
+# Define CUB_PTX_TARGETS to restrict the number of kernel tunings that are
+# instantiated. This is distinct from the logic in cub-config.cmake, since
+# CUB detects PTX arches after finding the CUB package.
+# After 11.5, __CUDA_ARCH_LIST__ should be available, and CUB will automatically
+# use that instead.
+if (CMAKE_CUDA_COMPILER_ID STREQUAL "NVIDIA" AND
+    CMAKE_CUDA_COMPILER_VERSION VERSION_LESS 11.5)
+  list(JOIN ptx_targets "\\," ptx_targets)
+  target_compile_definitions(_CUB_CUB INTERFACE "CUB_PTX_TARGETS=${ptx_targets}")
```
Comment (senior-zero) [inline cmake/CubCudaConfig.cmake:141]: I don't think `_CUB_CUB` is defined here when building CUB as a standalone project:
```bash
stderr 1: CMake Error at cmake/CubCudaConfig.cmake:141 (target_compile_definitions):
  Cannot specify compile definitions for target "_CUB_CUB" which is not built
  by this project.
```

**Comment by senior-zero** [comment]
I can see a lot of compilation errors when build with CTK 11.0, could you take a look?
```bash
cub/cub/cmake/../../cub/device/dispatch/dispatch_scan.cuh:169:57: error: unused parameter ‘d_in’ [-Werror=unused-parameter]
  169 | __global__ void DeviceScanKernel(InputIteratorT d_in,
      |                                         ~~~~~~~~~~~~~   ^   
cub/cub/cmake/../../cub/device/dispatch/dispatch_scan.cuh:170:1: error: unused parameter ‘d_out’ [-Werror=unused-parameter]
  169 | __global__ void DeviceScanKernel(InputIteratorT d_in,
      |                                                      
  170 |                                  OutputIteratorT d_out,
      | ^    
cub/cub/cmake/../../cub/device/dispatch/dispatch_scan.cuh:171:1: error: unused parameter ‘tile_state’ [-Werror=unused-parameter]
  170 |                                  OutputIteratorT d_out,
      |                                  ~~~~~~~~~~~~~~~~~~~~~~
  171 |                                  ScanTileStateT tile_state,
      | ^         
cub/cub/cmake/../../cub/device/dispatch/dispatch_scan.cuh:172:1: error: unused parameter ‘start_tile’ [-Werror=unused-parameter]
  171 |                                  ScanTileStateT tile_state,
      |                                  ~~~~~~~~~~~~~~~~~~~~~~~~~~
  172 |                                  int start_tile,
      | ^         
cub/cmake/../../cub/device/dispatch/dispatch_scan.cuh:173:1: error: unused parameter ‘scan_op’ [-Werror=unused-parameter]
  172 |                                  int start_tile,
      |                                  ~~~~~~~~~~~~~~~
  173 |                                  ScanOpT scan_op,
      | ^      
cub/cub/cmake/../../cub/device/dispatch/dispatch_scan.cuh:174:1: error: unused parameter ‘init_value’ [-Werror=unused-parameter]
  173 |                                  ScanOpT scan_op,
      |                                  ~~~~~~~~~~~~~~~~
  174 |                                  InitValueT init_value,
      | ^         
cub/cub/cmake/../../cub/device/dispatch/dispatch_scan.cuh:175:1: error: unused parameter ‘num_items’ [-Werror=unused-parameter]
  174 |                                  InitValueT init_value,
      |                                  ~~~~~~~~~~~~~~~~~~~~~~
  175 |                                  OffsetT num_items)
      | ^     
```

File: cub/detail/ptx_targets.cuh [hunk 2]
```diff
@@ -0,0 +1,117 @@
...
+#else // Non-doxygen pass:
+
+#ifndef CUB_PTX_TARGETS
+
+#ifdef __CUDA_ARCH_LIST__
+#define CUB_PTX_TARGETS __CUDA_ARCH_LIST__
+#elif defined(NV_TARGET_SM_INTEGER_LIST)
+
+// clang-format off
+#define CUB_DETAIL_PTX_TARGETS_NAME1(P1) \
```
Comment (senior-zero) [inline cub/detail/ptx_targets.cuh:63]: optional: we might potentially abstract this pattern by providing suffix and separator parameters.

File: cub/detail/type_list_impl.cuh [hunk 3]
```diff
@@ -0,0 +1,79 @@
...
+{};
+
+template <typename NewType, typename... OldTypes>
+struct prepend<type_list<OldTypes...>, NewType>
+{
+  using type = cub::detail::type_list<NewType, OldTypes...>;
+};
+
+template <typename NewType, typename... OldTypes>
+struct append<type_list<OldTypes...>, NewType>
```
Comment (senior-zero) [inline cub/detail/type_list_impl.cuh:72]: I'd be better to test all facilities in this file.

File: cub/device/dispatch/dispatch_adjacent_difference.cuh [hunk 4]
```diff
@@ -117,27 +116,16 @@ struct DeviceAdjacentDifferencePolicy
...
-      AgentAdjacentDifferencePolicy<128,
-                                    Nominal8BItemsToItems<ValueT>(7),
-                                    BLOCK_LOAD_WARP_TRANSPOSE,
-                                    MayAlias ? LOAD_CA : LOAD_LDG,
-                                    BLOCK_STORE_WARP_TRANSPOSE>;
-  };
-
-  using MaxPolicy = Policy350;
+  struct Policy350
+      : cub::detail::ptx_base<350>
```
Comment (senior-zero) [inline cub/device/dispatch/dispatch_adjacent_difference.cuh:120]: Is `_base` necessary? Can it be `ptx<350>` instead?

**Review by senior-zero — COMMENTED** [review]
The code looks much better now, thanks! A few minor notes below:

File: cub/detail/type_wrapper.cuh [hunk 5]
```diff
@@ -0,0 +1,43 @@
...
+
+CUB_NAMESPACE_BEGIN
+namespace detail
+{
+
+/** Wrapper used to pass types to functions without instantiating them. */
+template <typename T>
+struct type_wrapper
+{
+  using type = T;
```
[the remark this answers is not in the document]
Comment (allisonvacanti) [reply cub/detail/type_wrapper.cuh:39]: This isn't intended to interact with ADL, and ADL shouldn't be a concern in `ptx_dispatch`. `type_wrapper` just prevents `PtxType`s from requiring constructability.

File: cmake/CubCudaConfig.cmake (hunk 1 above)
Comment (allisonvacanti) [reply cmake/CubCudaConfig.cmake:141]: We should just prevent CUB from being used standalone at some point. Thrust + CUB submodule is preferred, especially for dev builds that would be hitting this code path.

But in the meantime, good catch! I'll fix this.

**Comment by allisonvacanti** [comment]
> I can see a lot of compilation errors when build with CTK 11.0, could you take a look?

Ack. I had an ugly WAR for these, but ended up upstreaming the fix to nvcc (NVBug 2431416). You're right, though, we still need it for older CTK -- I'll put the WAR back in.

File: cmake/CubCudaConfig.cmake [hunk 6]
```diff
@@ -3,9 +3,9 @@ enable_language(CUDA)
 #
 # Architecture options:
```
[the remark this answers is not in the document]
Comment (allisonvacanti) [reply cmake/CubCudaConfig.cmake:4]: I haven't seen this, and it hasn't popped up on CI. Still worrying though...

When this failed, were you running the tests in parallel (`cmake -j XX`)? Maybe there was a spurious OOM -> failed malloc -> nullptr -> segfault?

File: cub/detail/device_algorithm_dispatch_invoker.cuh [hunk 7]
```diff
@@ -0,0 +1,92 @@
...
+#pragma nv_exec_check_disable
+  template <typename Policy, typename DeviceAlgorithmDispatch, typename... Args>
+  __host__ __device__ __forceinline__
+  void operator()(cub::detail::type_wrapper<Policy> policy_wrapper,
+                  DeviceAlgorithmDispatch &&dispatch,
+                  Args &&...args)
+  {
+    this->impl(exec_space_tag<ExecSpace>{},
+               policy_wrapper,
+               std::forward<DeviceAlgorithmDispatch>(dispatch),
```
[the remark this answers is not in the document]
Comment (allisonvacanti) [reply cub/detail/device_algorithm_dispatch_invoker.cuh:55]: Good question. I'll make the switch, it would be preferable from a consistency standpoint.

File: test/test_device_segmented_sort.cu [hunk 8]
```diff
@@ -34,6 +34,9 @@
 
 #include <test_util.h>
```
[the remark this answers is not in the document]
Comment (allisonvacanti) [reply test/test_device_segmented_sort.cu:35]: Absolutely, thanks for pointing this out!

File: cub/device/dispatch/dispatch_adjacent_difference.cuh (hunk 4 above)
Comment (allisonvacanti) [reply cub/device/dispatch/dispatch_adjacent_difference.cuh:120]: I think so. The `_base` suffix is a leftover from when I had both `ptx_base` (intrusive) and `ptx_tag` (non-intrusive) versions of this functionality. The `tag` never got used, so it'd make sense to use the shorter name now.

File: cub/detail/type_wrapper.cuh (hunk 5 above)
[the remark this answers is not in the document]
Comment (allisonvacanti) [reply cub/detail/type_wrapper.cuh:39]: e.g. this way, the `ptx_dispatch` takes a functor that defines `operator()(type_wrapper<T>)` instead of `operator()(T)`.

I've run into issues with similar dispatch mechanisms when using types that required ctor arguments.

File: cmake/CubCudaConfig.cmake (hunk 1 above)
Comment (allisonvacanti) [reply cmake/CubCudaConfig.cmake:141]: Changed it to `cub.compiler_interface`.

File: cmake/CubCudaConfig.cmake (hunk 6 above)
[the remark this answers is not in the document]
Comment (senior-zero) [reply cmake/CubCudaConfig.cmake:4]: I haven't run tests in parallel.

File: cub/detail/type_wrapper.cuh (hunk 5 above)
[the remark this answers is not in the document]
Comment (senior-zero) [reply cub/detail/type_wrapper.cuh:39]: Is there anything blocking us from using the suggested implementation? Otherwise, we'd have to implement a second type wrapper at some point.

File: test/test_device_segmented_sort.cu (hunk 8 above)
[the remark this answers is not in the document]
Comment (allisonvacanti) [reply test/test_device_segmented_sort.cu:35]: Done (`test_ptx_dispatch.cu`)

File: cub/detail/type_list_impl.cuh (hunk 3 above)
Comment (allisonvacanti) [reply cub/detail/type_list_impl.cuh:72]: Done (`test_type_list.cu`)

**Review by senior-zero — COMMENTED** [review]
I've built our tests to compare new codegen with the previous one. There's quite a difference there:
```bash
:wc -l asm_old/cub.cpp17.test.device_reduce.cdp_0.types_0.asm
3389546 asm_old/cub.cpp17.test.device_reduce.cdp_0.types_0.asm
:wc -l asm_new/cub.cpp17.test.device_reduce.cdp_0.types_0.asm
34674 asm_new/cub.cpp17.test.device_reduce.cdp_0.types_0.asm
```
Am I missing something or there was some sort of a bug there? The build is for all supported architectures. Then:
```bash
for f in $(ls bin); do cuobjdump --dump-sass bin/$f > asm/$f.asm &; done
```
Could you take a look on your side?

File: cub/agent/agent_spmv_orig.cuh [hunk 9]
```diff
@@ -33,17 +33,20 @@
...
+#include <cub/block/block_reduce.cuh>
+#include <cub/block/block_scan.cuh>
+#include <cub/config.cuh>
+#include <cub/iterator/cache_modified_input_iterator.cuh>
+#include <cub/iterator/counting_input_iterator.cuh>
+#include <cub/thread/thread_operators.cuh>
+#include <cub/thread/thread_search.cuh>
+#include <cub/util_type.cuh>
+
+#include <nv/target>
```
Comment (miscco) [inline cub/agent/agent_spmv_orig.cuh:46]: Is there a certain order this include must go in? Should we add `<nv/` as another include block in the clang-format file?

File: cub/agent/agent_spmv_orig.cuh [hunk 10]
```diff
@@ -458,22 +429,37 @@ struct AgentSpmv
...
-                ValueT  value                   = wd_values[tile_start_coord.y + nonzero_idx];
-
-                ValueT  vector_value            = wd_vector_x[column_idx];
+                int nonzero_idx = threadIdx.x + (ITEM * BLOCK_THREADS);
 
-                ValueT  nonzero                 = value * vector_value;
+                // clang-format off
+                NV_IF_TARGET(NV_PROVIDES_SM_52,
+                (
+                    auto a = wd_values + tile_start_coord.y + nonzero_idx;
```
Comment (miscco) [inline cub/agent/agent_spmv_orig.cuh:437]: Is there a reason we need those computations outside of the if?

and obligatory hiss at one letter variable names

File: cub/detail/device_algorithm_dispatch_invoker.cuh [hunk 11]
```diff
@@ -0,0 +1,94 @@
...
+  CUB_EXEC_CHECK_DISABLE
+  template <typename Policy, typename DeviceAlgorithmDispatch, typename... Args>
+  __host__ __device__ __forceinline__
+  void operator()(cub::detail::type_wrapper<Policy> policy_wrapper,
+                  DeviceAlgorithmDispatch &&dispatch,
+                  Args &&...args)
+  {
+    this->impl(exec_space_tag<ExecSpace>{},
+               policy_wrapper,
+               std::forward<DeviceAlgorithmDispatch>(dispatch),
```
Comment (miscco) [inline cub/detail/device_algorithm_dispatch_invoker.cuh:57]: Should those be `cuda::std::forward`? Because I am not sure whether `std::forward` has `__host__ __device__` on it

File: cub/detail/ptx_dispatch.cuh [hunk 12]
```diff
@@ -0,0 +1,144 @@
...
+ *
+ * ```
+ * struct Foo600 : cub::detail::ptx<600> { ... };
+ * struct Foo800 : cub::detail::ptx<800> { ... };
+ *
+ * // `type_list` for use with `ptx_dispatch`:
+ * using FooList = cub::detail::type_list<Foo800, Foo600>;
+ * ```
+ *
+ * \tparam PtxArch 3-digit PTX architecture version (e.g. 800 for Ampere)
```
Comment (miscco) [inline cub/detail/ptx_dispatch.cuh:55]: That comment might become stale quickly should we drop the "3-digit"

File: cub/detail/ptx_dispatch_impl.cuh [hunk 13]
```diff
@@ -0,0 +1,464 @@
...
+  }
+};
+
+template <>
+struct ptx_dispatch_host_impl<type_list<>>
+{
+  template <typename Functor, typename... Args>
+  __host__ __forceinline__ static void exec(int /* target_ptx_arch */, Functor &&, Args &&...)
+  {
+    // Didn't find a matching arch.
```
Comment (miscco) [inline cub/detail/ptx_dispatch_impl.cuh:311]: should there be an assert here or something?

File: cub/detail/type_traits.cuh [hunk 14]
```diff
@@ -37,10 +37,30 @@
 
 #include <cuda/std/type_traits>
 
+#include <iterator>
```
Comment (miscco) [inline cub/detail/type_traits.cuh:40]: Should that be 
```suggestion
#include <cuda/std/iterator>
```

File: docs/developer_overview.md [hunk 15]
```diff
@@ -404,51 +404,64 @@ cudaError_t cub::Device::Algorithm(args) {
...
-cudaError_t ChainedPolicy::Invoke(ptx_version, invokable) { // (2)
-  if (ptx_version < ChainedPolicy::PTX_VERSION) {
-    ChainedPolicy::PrevPolicy::Invoke(ptx_version, invokable); // (2)
-  } 
-  invokable.Invoke<ChainedPolicy::PTX_VERSION>(); // (3)
+  // A cub::detail::type_list of tuning policies:
+  using policies_t = typename DispatchAlgorithm::Policies;
+
+  // The execution spaces supported by the invokable
+  // (ie. host/device/host_device). `runtime_exec_space` is `host_device` when
```
Comment (miscco) [inline docs/developer_overview.md:414]: Could we move the second sentence to its own line

**Review by miscco — APPROVED** [review]
So my knowledge about the dispatch mechanisms is limited, so everything here is with a grain of salt.

I believe the new implementation manages to be less eldritchy than the previous. one.

I am fine with not trying to do ADL isolation right now, as that adds quite a bit to compile times due to the additional instantiations required. It is only a problem when the target functions are overloaded, which might be a problem for `copy(in, in , out)` but I would wager we are fine here.

I am fine with being strict about the ordering and uniqueness of the archs, that is on our plate and we should take care there.

**Comment by jrhemstad** [comment]
@allisonvacanti and I talked and we agreed to close this PR for now as this work has been de-prioritized. We will pick it back up if/when it becomes a priority again.
